services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: klopf
      DOCKER_INFLUXDB_INIT_BUCKET: traffic
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-token
    volumes:
      - influxdb-data:/var/lib/influxdb2

  control:
    build:
      context: ./services/control
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: my-super-secret-token
      INFLUX_ORG: klopf
      INFLUX_BUCKET: traffic
      DB_PATH: /data/control.db
    volumes:
      - control-data:/data
    depends_on:
      - mosquitto
      - influxdb

  # cv:
  #   build:
  #     context: ./services/cv
  #   restart: unless-stopped
  #   depends_on:
  #     - mosquitto

  # web:
  #   build:
  #     context: ./services/web
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - control

volumes:
  influxdb-data:
  control-data:
